server:
  port: 9300
# netty通信
netty:
  server:
    port: 1212

app:
  application:
    # 服务名称
    name:
      route
  registry:
    # 注册中心地址
    address: localhost:2181
  protocol:
    # 开放端口
    port: 2300